// <auto-generated />
using LandingPageItBeep.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LandingPageItBeep.Migrations
{
    [DbContext(typeof(LandingPageItBeepContext))]
    [Migration("20191004084804_AddLookupCategoriesRelationship")]
    partial class AddLookupCategoriesRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LandingPageItBeep.Models.Lookup", b =>
                {
                    b.Property<int>("LookupID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CraetedBy");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LookupName");

                    b.Property<string>("LookupNameEn");

                    b.HasKey("LookupID");

                    b.ToTable("Lookups");
                });

            modelBuilder.Entity("LandingPageItBeep.Models.LookupCategory", b =>
                {
                    b.Property<int>("LookupCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CraetedBy");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("LookupID");

                    b.Property<string>("LookupName");

                    b.Property<string>("LookupNameEn");

                    b.HasKey("LookupCategoryID");

                    b.HasIndex("LookupID");

                    b.ToTable("LookupCategory");
                });

            modelBuilder.Entity("LandingPageItBeep.Models.LookupCategory", b =>
                {
                    b.HasOne("LandingPageItBeep.Models.Lookup", "Lookup")
                        .WithMany("LookupCategories")
                        .HasForeignKey("LookupID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
